version: '3'

services:
  go-service:
    container_name: laundry-be
    build:
      context: .
      dockerfile: Dockerfile
    image: laundry-be
    ports:
      - "3400:3400"
    links:
      - db-service
    depends_on:
      - db-service
    tty: true
    network_mode: bridge
  db-service:
    container_name: laundry-db
    image: mysql:latest
    ports:
      - "3401:3306"
    volumes:
         - ./config/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: laundry
      MYSQL_USER: laundry
      MYSQL_PASSWORD: laundry
      MYSQL_DATABASE: laundry
    tty: true
    network_mode: bridge

# vim set ft=2 ts=2 expandtab:
