---
database:
  host: db-service
  port: 3306
  database: laundry
  username: laundry
  password: laundry

http:
  listen: ':3400'

bookings:
  max_allowed: 1
  min_slot_duration: 3

administration:
  support_email: landlord@example.com

# vim: set sw=2 ts=2 expandtab:
