---
database:
  host: laundry-db
  database: laundry
  username: laundry
  password: laundry

http:
  listen: ':3000'

bookings:
  max_allowed: 1
  min_slot_duration: 3

administration:
  support_email: landlord@example.com

# vim: set sw=2 ts=2 expandtab:
